[package]
name = "primacy_bis"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
rulinalg = "0.4.2"
rand_distr = "0.4.3"
rand = "0.8.5"
# duration-string = "0.2.0"